"""S3/R2 audio upload helpers.

Cloudflare R2 is S3-compatible, so we use boto3 against the R2 endpoint.
The bucket is private — recordings are served via short-lived presigned URLs
generated by the Next.js /api/recording/:sessionId/url route.
"""

from __future__ import annotations

import io
import os
import wave
from typing import Optional

from loguru import logger


def _r2_client():
    """Lazy-import boto3 so the bot starts without it installed in dev."""
    import boto3
    from botocore.config import Config

    account_id = os.getenv("R2_ACCOUNT_ID")
    key_id = os.getenv("R2_ACCESS_KEY_ID")
    key_secret = os.getenv("R2_SECRET_ACCESS_KEY")
    if not (account_id and key_id and key_secret):
        return None

    return boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=key_id,
        aws_secret_access_key=key_secret,
        region_name="auto",
        config=Config(signature_version="s3v4"),
    )


def pcm_to_wav(pcm: bytes, sample_rate: int, num_channels: int) -> bytes:
    """Wrap raw PCM (s16le) into a WAV container."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(num_channels)
        wf.setsampwidth(2)  # 16-bit PCM
        wf.setframerate(sample_rate)
        wf.writeframes(pcm)
    return buf.getvalue()


def upload_session_audio(
    *,
    session_id: str,
    pcm: bytes,
    sample_rate: int,
    num_channels: int,
) -> Optional[str]:
    """Upload a session's recording to R2. Returns the s3:// URI on success.

    No-op (returns None) if R2 isn't configured — useful for local dev.
    """
    if not pcm:
        logger.info("luna: empty audio buffer; skipping upload")
        return None

    client = _r2_client()
    bucket = os.getenv("R2_BUCKET", "luna-recordings")
    if not client:
        logger.warning("luna: R2 not configured; recording dropped")
        return None

    key = f"sessions/{session_id}.wav"
    wav = pcm_to_wav(pcm, sample_rate=sample_rate, num_channels=num_channels)

    try:
        client.put_object(
            Bucket=bucket,
            Key=key,
            Body=wav,
            ContentType="audio/wav",
            Metadata={"session_id": session_id},
        )
    except Exception:
        logger.exception("luna: R2 upload failed")
        return None

    logger.info(f"luna: uploaded recording r2://{bucket}/{key}")
    return f"r2://{bucket}/{key}"
