// Splash — server-rendered. Brand identity is read from env so changing
// BRAND_NAME / TAGLINE updates the wordmark and metadata without a
// redeploy. Headline + subtitle are generated by a cheap LLM (OpenAI
// nano by default, Sarvam fallback) and cached per (brand × time-of-day)
// in the splash_copy table.

import { cookies } from 'next/headers';
import { LunaSplash } from '@/components/luna-splash';
import { ensureUser } from '@/lib/auth';
import { readBrandFromEnv } from '@/lib/brand';
import {
  getOrGenerateSplashCopy,
  timeOfDayFromHour,
} from '@/lib/splash-copy';
import { GUEST_COOKIE_NAME, verifyGuestCookie } from '@/lib/guest-cookie';
import { findAnonymousUser } from '@/lib/anonymous';
import { loadRecallSummary, copyForRecall } from '@/lib/recall';

export const dynamic = 'force-dynamic';

// Time-of-day on the server is always IST — the product is anchored to
// India even when accessed from elsewhere, and we want the late-night
// register at 1am IST regardless of the visitor's timezone. Switch to
// `Intl.DateTimeFormat` if you ever want per-user timezone resolution.
function currentISTHour(): number {
  const fmt = new Intl.DateTimeFormat('en-US', {
    timeZone: 'Asia/Kolkata',
    hour: 'numeric',
    hour12: false,
  });
  return parseInt(fmt.format(new Date()), 10);
}

export default async function HomePage() {
  const me = await ensureUser();
  const brand = readBrandFromEnv();

  const tod = timeOfDayFromHour(currentISTHour());
  const copy = await getOrGenerateSplashCopy(brand.brandName, tod);

  let recallCopy: string | null = null;
  const c = await cookies();
  const raw = c.get(GUEST_COOKIE_NAME)?.value;
  if (raw) {
    const v = verifyGuestCookie(raw);
    if (v.ok) {
      const anon = await findAnonymousUser(v.payload.userId);
      if (anon) {
        const r = await loadRecallSummary(anon.id);
        if (r) recallCopy = copyForRecall(r);
      }
    }
  }

  return (
    <main className="screen fade-in">
      <LunaSplash
        signedIn={!!me}
        brandName={brand.brandName}
        headline={copy.headline}
        subtitle={copy.subtitle}
        recallCopy={recallCopy}
      />
    </main>
  );
}
